Update to allow SSL to work.
vmware-archive/node-examples pull request #3
Opened 2020-02-04 23:20 UTC by charliemblack

Put in the flag to allow any node 10 to work.

2020-02-05 16:48 UTC, pdxcodemonkey requested changes
This will no longer run locally in our dev or CI environments.  Can you please modify startGemFire/shutdownGemFire scripts to start server/locator with SSL enabled and modify the book-service code somehow to support switching cert files so we can run it locally?

2020-02-05 17:15 UTC, mmartell commented
Maybe just use an environment variable (PCC-ENABLED) to allow running in PCC as well as locally and in CI. Select the system's truststore when PCC-ENABLED is true.

2020-02-05 17:18 UTC, mmartell commented
Also noticed that the README.md has 10.16.3 as minimum version on Node.js, whereas 10.0 is minimum version in package.json.

2020-02-05 17:31 UTC, charliemblack commented
Mike - I like the environ variable idea.    Node has a
`NODE_ENV=production` when it's running on cloud foundry.   The default is
considered development.

Charlie

On Wed, Feb 5, 2020 at 9:18 AM Michael Martell <notifications@github.com>
wrote:

> Also noticed that the README.md has 10.16.3 as minimum version on Node.js,
> whereas 10.0 is minimum version in package.json.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gemfire/node-examples/pull/3?email_source=notifications&email_token=AARHCKUJSD33CYPFHQQ3ROLRBLYFDA5CNFSM4KQAENO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK4HX5Q#issuecomment-582515702>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARHCKVM5WT7GU2C6H3ZIBTRBLYFDANCNFSM4KQAENOQ>
> .
>

2020-02-06 21:20 UTC, karensmolermiller reviewed
I don't really think that the prose that explains how to spin up a Cloud Cache cluster is necessary anymore. It existed because the example did not work when TLS encryption was enabled, so we wanted to make extra sure that users spun up a non-TLS encrypted cluster. 

I suggest accepting this PR and then asking Dave Barnes (@davebarnes97) to look at the README.

2020-02-06 21:21 UTC, karensmolermiller commented on book-service/README.md
>  1. Create a Cloud Cache service instance that disables TLS encryption. For example:
Change "disabled" to "enabled"

2020-02-07 20:04 UTC, charliemblack commented on book-service/README.md
>  1. Create a Cloud Cache service instance that disables TLS encryption. For example:
done

2020-02-07 20:07 UTC, charliemblack commented
looks like the review is still thinking I need changes - but I don't see anything to resolve.    I believe I resolved all open issues.

2020-02-07 20:27 UTC, pdxcodemonkey approved these changes

2020-02-07 20:29 UTC, merged